[package]
name = "countries"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "countries"

[features]
default = ["uniffi/cli"]

[dependencies]
uniffi = { version = "=0.29.1" }

[build-dependencies]
uniffi = { version = "=0.29.1", features = ["build"] }
